### ISSUE TITLE
v1.3.2-alpha.2 这个 tag 是不是被删了? 导致 polaris-go 引用报错

### ISSUE THREAD

**Issue by mason51** [polarismesh/specification#89]
https://github.com/polarismesh/polaris-go/blob/v1.5.1/go.mod

![image](https://github.com/polarismesh/specification/assets/130734565/78966dc4-5b14-4cf0-a5ed-b263f56596ac)

github.com/polarismesh/specification@v1.3.2-alpha.2: reading github.com/polarismesh/specification/go.mod at revision v1.3.2-alpha.2: unknown revision v1.3.2-alpha.2

**Comment by chuntaojun** [comment]
更新 polaris-go 到 1.5.3

**Comment by mason51** [comment]
因为不是直接引入的, 排查了好几层, 才发现是这里的问题. 
涉及到的链条有点长,  我也想更新, 但暂时更新不了. 请问tag能打回来吗?

**Comment by chuntaojun** [comment]
1.5.1 存在别的问题，建议升级到 1.5.3
